### ISSUE TITLE
Support for Bean Validation 3

### ISSUE THREAD

**Issue by aburmeis** [openapi-processor/openapi-processor-core#105]
[Bean Validation 3](https://beanvalidation.org/3.0/) has moved the package of the annotations from `javax.validation` to `jakarta.validation`. The generated code with option `bean-validation: true` is no longer compatible with the current version. The same problem occurs also for the spring processor which no longer works with Spring Boot 3.

**Comment by hauner** [comment]
already implemented https://github.com/openapi-processor/openapi-processor-spring/issues/152 ! :-)

but not yet released

**Comment by aburmeis** [comment]
great, also just found the issue. Thanks!
