### ISSUE TITLE
Format mapping on primitive type not work

### ISSUE THREAD

**Issue by schlagi123** [openapi-processor/openapi-processor-core#22]
I have the following typ:
```
UUID:
  type: string
```
and try to map it to a java UUID type:
```
map:
  types:
    - type: UUID => java.util.UUID
```
The result of the generated Interface is, that the UUID typ will generated in a String.

If I change the type of UUID to object, it works correctly. My read is, that mapping for primitive types not work.

**Comment by hauner** [comment]
I have a fix that accepts the above mapping :-)

A few notes (after the fix on the processor side):

- both parser (swagger & openapi4j) do not read anything in the root api file, if it is not under a specified (or allowed) key
- e.g. `#/components/schemas/UUID` works for both but `#/foo/UUID` does not
- `#/x-foo/UUID` (x- is the extension prefix which is allowed at the root level) gets excepted by both but the mapping only works with openapi4j. swagger does not seem to recognize it as a proper `schema` and the mapping fails. 
  Not sure if this is a bug or if openapi4j just accepts more than it has to.

Still have to check how it behaves with a $ref to another file.
