### ISSUE TITLE
Support for pattern Bean Validation

### ISSUE THREAD

**Issue by schlagi123** [openapi-processor/openapi-processor-core#63]
Hi,
it would be great, if the generator could resolve the pattern property (in models) to a @Pattern annotation (Bean Validation)

**Comment by hauner** [comment]
available in 2021.4-SNAPSHOT, you can test it by adding it to the processor configuration.

Example:

  ```groovy
  // ...
  spring {
     processor 'io.openapiprocessor:openapi-processor-core:2021.4-SNAPSHOT'
     processor 'io.openapiprocessor:openapi-processor-spring:2021.3.1'
     // ...
  }
  ```
