### ISSUE TITLE
marker interface for oneOf?

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-core#78]
Is it worth adding a marker interface to the items of `oneOf` that's used as the type instead of `Object`?

moved `anyOf` to #90, one step at a time

**Comment by davidjohnstonverint** [comment]
Yes please :D

**Comment by davidjohnstonverint** [comment]
Will the fields that reference the marker interface be given the @Valid annotation?

**Comment by hauner** [comment]
of course ;-)

**Comment by hauner** [comment]
released in `io.openapiprocessor:openapi-processor-spring:2022.3`
